version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
       - npm install --force
       - npm install ts-node --force
       - npm install -g typescript --save-dev @types/node --force
       - npm install express --force
       - npm install --silent --no-progress -g npm --force
  pre_build:
  commands:
    - echo "Generando archivo .env"
    - echo "PORT=$PORT" >> .env
    - echo "DB_CONN_STRING=$DB_CONN_STRING" >> .env
    - echo "DB_CONN_STRING_PRODUCTION=$DB_CONN_STRING_PRODUCTION" >> .env
    - echo "PROJECT_ID=$PROJECT_ID" >> .env
    - echo "PRIVATE_KEY=$PRIVATE_KEY" >> .env
    - echo "CLIENT_EMAIL=$CLIENT_EMAIL" >> .env

  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - package.json
    - package-lock.json
    - build/**/*
    - '.platform/**/*'
    - '.ebextensions/**/*'
    - '.elasticbeanstalk/**/*'
    - .env
  discard-paths: no