version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
       - npm install ts-node --force
       - npm install -g typescript --save-dev @types/node --force
       - npm install express --force
       - npm install --silent --no-progress -g npm --force
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - package.json
    - package-lock.json
    - build/**/*
    - '.platform/**/*'
    - '.ebextensions/**/*'
    - '.elasticbeanstalk/**/*'
    - .env
  discard-paths: no